# Generated by Django 4.2.3 on 2023-07-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(choices=[('SUN', 'Sun Expres'), ('THY', 'Turkish Airlines'), ('PEG', 'Pegasus')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.PositiveSmallIntegerField(choices=[(44, 'Malatya'), (10, 'Balıkesir'), (52, 'Ordu'), (6, 'Ankara'), (34, 'Istanbul'), (7, 'Antalya'), (9, 'Aydın'), (35, 'Izmir'), (1, 'Adana'), (16, 'Bursa'), (32, 'Isparta')]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.PositiveSmallIntegerField(choices=[(44, 'Malatya'), (10, 'Balıkesir'), (52, 'Ordu'), (6, 'Ankara'), (34, 'Istanbul'), (7, 'Antalya'), (9, 'Aydın'), (35, 'Izmir'), (1, 'Adana'), (16, 'Bursa'), (32, 'Isparta')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('0', 'Undefined'), ('F', 'Female'), ('M', 'Male')], default='0', max_length=1),
        ),
    ]
