# Generated by Django 4.2.3 on 2023-07-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_flight_airline_alter_flight_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(choices=[('THY', 'Turkish Airlines'), ('PEG', 'Pegasus'), ('SUN', 'Sun Expres')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.PositiveSmallIntegerField(choices=[(9, 'Aydın'), (44, 'Malatya'), (7, 'Antalya'), (10, 'Balıkesir'), (52, 'Ordu'), (16, 'Bursa'), (34, 'Istanbul'), (1, 'Adana'), (35, 'Izmir'), (32, 'Isparta'), (6, 'Ankara')]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.PositiveSmallIntegerField(choices=[(9, 'Aydın'), (44, 'Malatya'), (7, 'Antalya'), (10, 'Balıkesir'), (52, 'Ordu'), (16, 'Bursa'), (34, 'Istanbul'), (1, 'Adana'), (35, 'Izmir'), (32, 'Isparta'), (6, 'Ankara')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('0', 'Undefined'), ('F', 'Female')], default='0', max_length=1),
        ),
    ]
