# Generated by Django 4.2.3 on 2023-07-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_flight_airline_alter_flight_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(choices=[('THY', 'Turkish Airlines'), ('SUN', 'Sun Airlines'), ('SEL', 'Selim Airlines')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Adana'), (6, 'Ankara'), (7, 'Antalya'), (9, 'Aydın'), (10, 'Balıkesir'), (16, 'Bursa'), (32, 'Isparta'), (34, 'Istanbul'), (35, 'Izmir'), (44, 'Malatya'), (52, 'Ordu')]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Adana'), (6, 'Ankara'), (7, 'Antalya'), (9, 'Aydın'), (10, 'Balıkesir'), (16, 'Bursa'), (32, 'Isparta'), (34, 'Istanbul'), (35, 'Izmir'), (44, 'Malatya'), (52, 'Ordu')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('0', 'Prefer Not To Say')], default='0', max_length=1),
        ),
    ]
